# Tên của kịch bản
name: Fetch News RSS

# Lịch chạy: Chạy tự động 30 phút một lần
on:
  schedule:
    - cron: '*/30 * * * *'
  # Dòng này cho phép bạn chạy thủ công (để test)
  workflow_dispatch:

# Các công việc cần làm
jobs:
  fetch-rss:
    # Chạy trên một máy ảo Ubuntu (do GitHub cung cấp)
    runs-on: ubuntu-latest
    
    # Cấp quyền cho kịch bản để nó có thể "lưu" file vào kho chứa
    permissions:
      contents: write

    steps:
      # Bước 1: Tải code từ kho chứa của bạn về máy ảo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Cài đặt Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Bước 3: Cài đặt thư viện Python (feedparser) để đọc RSS
      - name: Install dependencies
        run: |
          pip install feedparser

      # Bước 4: Chạy script Python để tải và phân tích RSS
      - name: Fetch and Parse RSS
      
        # *** DÒNG SỬA LỖI QUAN TRỌNG: ***
        # Báo cho GitHub Actions dùng "python" để chạy, không dùng "bash"
        shell: python 
        
        run: |
          import feedparser
          import json
          import os

          # Dùng RSS của Dân Trí
          RSS_URL = "https://dantri.com.vn/rss/home.rss"
          
          # Giả mạo làm trình duyệt Firefox để tránh bị chặn
          USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0"
          
          # Tải và phân tích (có thêm User-Agent)
          print(f"Fetching RSS from {RSS_URL} with User-Agent...")
          feed = feedparser.parse(RSS_URL, agent=USER_AGENT)
          
          # Kiểm tra xem có lấy được tin không
          if not feed.entries:
              print("Error: Could not fetch RSS entries. Feed might be blocking or empty.")
              # Tạo file JSON rỗng để không làm sập ESP32
              json_output = {"headlines": ["Lỗi: Không thể tải tin tức."]}
          else:
              print(f"Successfully fetched {len(feed.entries)} entries.")
              headlines = []
              # Lấy 3 tiêu đề đầu tiên
              for entry in feed.entries[:3]:
                  headlines.append(entry.title)
              
              # Tạo nội dung JSON
              json_output = {
                  "headlines": headlines
              }
          
          # Ghi ra file news.json
          with open('news.json', 'w', encoding='utf-8') as f:
              json.dump(json_output, f, ensure_ascii=False, indent=2)
          
          print("news.json file created successfully.")
          print(f"Current directory content: {os.listdir('.')}")

      # Bước 5: Lưu file news.json mới vào kho chứa
      - name: Commit and Push new news.json
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add news.json
          # Chỉ lưu nếu có thay đổi
          git commit -m "Update news.json with latest headlines" || echo "No changes to commit"
          git push
